ArraysUtils added
emiryazicii/TeamCollab_Group32 pull request #1
Opened 2024-01-21 22:29 UTC by bataborisa

I have added some ArraysUtil methods

2024-01-21 22:47 UTC, emiryazicii reviewed
Thanks Boris, It looks great. We will discuss what methods we can write in that class.
I just want to remind you , it will be perfect if you can make a pull request to 'develop' branch instead 'master' branch directly.

2024-01-21 22:48 UTC, emiryazicii commented on src/utils/ArraysUtils.java
> +    // methods we need
That will be great add some methods here later on.For now it looks good enough.

2024-01-21 22:50 UTC, emiryazicii commented
I just want to remind you That will be perfect if you can make a pull request to develop branch instead master branch directly.

2024-01-21 23:07 UTC, emiryazicii requested changes
Can you please send the pull request to "develop" branch.

2024-01-22 16:21 UTC, closed without merging

2024-01-22 16:21 UTC, bataborisa commented
I did change mine pull request, so now is from my name Branch to Devalop branch, hope now everything will be at right place

2024-01-22 16:22 UTC, emiryazicii commented
Thanks for update.